import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { Header } from '@/components/header';
import { getUser } from './actions/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers user={user}>
          <Header />
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  );
}
